# This is a demo workflow to run the tests in matrix set up

name: tests in matrix
on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/test/resources/test-ds.xml' 
      - 'src/test/java/org/jboss/as/quickstarts/kitchensink/test/MemberRegistrationIT.java' 

jobs:
  matrix_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Java to ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Download wildfly server and start the testing
      run: |
        wget -q https://download.jboss.org/wildfly/19.0.0.Final/wildfly-19.0.0.Final.zip
        unzip -q wildfly-19.0.0.Final.zip
        JBOSS_HOME="$GITHUB_WORKSPACE/wildfly-19.0.0.Final"
        export JBOSS_HOME
        echo "JBOSS_HOME: $JBOSS_HOME"
        java --version
        mvn --version
        mvn clean test -B -Parq-managed -Dtest=MemberRegistrationIT

